learning_users/basic_app/urls.py
from django.urls import path,include
from basic_app import views

app_name = "basic_app"

urlpatterns = [
    path('',views.index,name="index"),
    path('basic_app/register/',views.register,name="register"),
    path('basic_app/login/',views.user_login,name="login"),
    path('basic_app/special/',views.special,name="special"),
    path('basic_app/logout/',views.user_logout,name="logout"),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('basic_app.urls')),
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #Addtional attributes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout

# Create your views here.

def index(request):
    return render(request,"basic_app/index.html")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('basic_app:index'))

@login_required
def special(request):
    return render(request,"basic_app/special.html")

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,"basic_app/register.html",
                    {'user_form':user_form,'profile_form':profile_form,'registered':registered})


def user_login(request):
    if request.method=="POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('basic_app:index'))

            else:
                return HttpResponse("Your account has been deactivated")
        else:
            print("Someone tried to login and failed")
            print(f"Username: {username} \n Password: {password}")
            return HttpResponse("Invalid Login credentials")
    else:
        return render(request,"basic_app/login.html")

learning_users/templates/basic_app/base.html
<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url "basic_app:index" %}">Home Page</a></li>
          <li class="nav-item"><a  class="nav-link active" aria-current="page" href="{% url "admin:index" %}">Admin</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url "basic_app:register" %}">Register</a></li>
          {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="{% url "basic_app:special" %}">Special</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url "basic_app:logout" %}">Logout</a></li>

          {% else %}
          <li class="nav-item"><a class="nav-link" href="{% url "basic_app:login" %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container">

      {% block body_block %}
      {% endblock %}

    </div>

  </body>
</html>

learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html"  %}
{% load static %}

{% block body_block %}

<h1>Wecome to home page</h1>

<img src="{% static "basic_app/images/homepage.jpg" %}" alt="Sorry, Image cannot be displayed!!!" width="700" height="700">
{% endblock %}

learning_users/templates/basic_app/login.html
{% extends "basic_app/base.html" %}

{% block body_block %}

<div class="container">

  <div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url "basic_app:login" %}" method="post">
      {% csrf_token %}
      <label for="username">Username: </label>
      <input type="text" name="username" placeholder="Enter username">

      <label for="password">Password: </label>
      <input type="password" name="password">

      <input type="submit" name="" value="Login">
    </form>
  </div>
</div>
{% endblock %}

learning_users/templates/basic_app/register.html
{% extends "basic_app/base.html" %}
{% load static %}

{% block body_block %}
  <div class="jumbotron">
    {% if registered %}
      <h1>Thank you for registering</h1>
    {% else %}
    <h1>Rgister here</h1>
    <h2>Fill out the form:</h2>
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">
    </form>
    {% endif %}
  </div>
{% endblock %}

learning_users/templates/basic_app/special.html
{% extends "basic_app/base.html" %}
{% load static %}

{% block body_block %}
<br>
<embed type="" src="{% static "basic_app/videos/PythonIntro.mp4" %}" width="300" height="300">

{% endblock %}